CREATE TABLE IF NOT EXISTS `websites`(
    `id` INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(200) NOT NULL,
    `url` VARCHAR(200) NOT NULL,
    `alexa` VARCHAR(50) NOT NULL,
    `country` VARCHAR(50) NOT NULL 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;